os:
  - linux

dist: xenial

language: python
addons:
  sonarcloud:
    organization: "testgopal"
    token:
      secure: $SONAR_TOKEN # encrypted value of your token

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - sonar-scanner
script:
  - python -m pytest -v
  - sonar-scanner
